/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Generates the react-native-tvos release metadata table.
 *
 * Released versions come from npm dist-tags, not git tags. The fork's
 * repository also carries inherited upstream core React Native tags (v0.87.1,
 * v0.86.3), which are not TV releases; and the fork's own `-N` suffix means
 * "newer", the opposite of semver's prerelease ordering, so sorting git tags
 * with a semver library picks the wrong release. The `<version>-stable`
 * dist-tags published to npm are authoritative.
 *
 * Per-version platform requirements are read through `git show` at each
 * `tvos-v<version>.0` ref.
 *
 * Usage: node scripts/src/generate-tv-releases.ts [--repo=<path>] [--check]
 */

import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

import {
  REPO_ROOT,
  assertIsTvBranch,
  readAtRef,
  readSourceConfig,
  resolveCheckout,
} from './lib/rntv-source.ts';

const NPM_PACKAGE = 'react-native-tvos';

const OUT_JSON = path.join(REPO_ROOT, 'website', 'tv-releases.json');
const OUT_TABLE = path.join(
  REPO_ROOT,
  'website',
  'releases',
  '_tv-branches-table.md'
);

type Release = {
  version: string;
  npmVersion: string;
  branch: string;
  react: string;
  minTvos: string;
  minSdk: string;
  targetSdk: string;
  compileSdk: string;
  ndkVersion: string;
};

/** Maps `<version>-stable` npm dist-tags to published versions. */
function npmDistTags(): Map<string, string> {
  const raw = execFileSync(
    'npm',
    ['view', NPM_PACKAGE, 'dist-tags', '--json'],
    {encoding: 'utf8', maxBuffer: 8 * 1024 * 1024}
  );
  const tags: Record<string, string> = JSON.parse(raw);
  const byVersion = new Map<string, string>();
  for (const [tag, version] of Object.entries(tags)) {
    const match = /^(\d+\.\d+)-stable$/.exec(tag)?.[1];
    if (match) {
      byVersion.set(match, version);
    }
  }
  return byVersion;
}

function matchOrThrow(text: string, re: RegExp, what: string): string {
  const captured = re.exec(text)?.[1];
  if (captured === undefined) {
    throw new Error(
      `Could not read ${what}. The source layout may have changed.`
    );
  }
  return captured;
}

function readRelease(
  repo: string,
  version: string,
  npmVersion: string
): Release {
  const branch = `tvos-v${version}.0`;
  assertIsTvBranch(repo, branch);

  const pkg = JSON.parse(
    readAtRef(repo, branch, 'packages/react-native/package.json')
  );
  const react = pkg.peerDependencies?.react;
  if (!react) {
    throw new Error(`No react peer dependency at ${branch}.`);
  }

  const gradle = readAtRef(
    repo,
    branch,
    'packages/react-native/gradle/libs.versions.toml'
  );
  const podHelpers = readAtRef(
    repo,
    branch,
    'packages/react-native/scripts/cocoapods/helpers.rb'
  );

  return {
    version,
    npmVersion,
    branch,
    react,
    minTvos: matchOrThrow(
      podHelpers,
      /def self\.min_ios_version_supported\s*\n\s*return '([\d.]+)'/,
      `min tvOS version at ${branch}`
    ),
    minSdk: matchOrThrow(gradle, /^minSdk = "(\d+)"/m, `minSdk at ${branch}`),
    targetSdk: matchOrThrow(
      gradle,
      /^targetSdk = "(\d+)"/m,
      `targetSdk at ${branch}`
    ),
    compileSdk: matchOrThrow(
      gradle,
      /^compileSdk = "(\d+)"/m,
      `compileSdk at ${branch}`
    ),
    ndkVersion: matchOrThrow(
      gradle,
      /^ndkVersion = "([\d.]+)"/m,
      `ndkVersion at ${branch}`
    ),
  };
}

const TREE_URL = 'https://github.com/react-native-tvos/react-native-tvos/tree';

function renderTable(releases: Release[]): string {
  const rows = releases.map(r =>
    [
      `[\`${r.branch}\`](${TREE_URL}/${r.branch})`,
      `\`${r.npmVersion}\``,
      `[\`${r.version}\`](https://reactnative.dev/versions)`,
      `\`${r.react}\``,
      `\`${r.minTvos}\``,
      `\`${r.minSdk}\``,
      `\`${r.targetSdk}\` / \`${r.compileSdk}\``,
      `\`${r.ndkVersion}\``,
    ].join(' | ')
  );
  // Imported into an MDX page, so HTML comments are a syntax error here.
  return [
    '{/* @generated by scripts/src/generate-tv-releases.ts.',
    '    Do not edit by hand; run `yarn generate:tv-releases`. */}',
    '',
    '| Branch | `react-native-tvos` | Core RN | React | Min tvOS | Android `minSdk` | `targetSdk` / `compileSdk` | NDK |',
    '| ------ | ------------------- | ------- | ----- | -------- | ---------------- | -------------------------- | --- |',
    ...rows.map(row => `| ${row} |`),
    '',
  ].join('\n');
}

async function writeIfChanged(
  filePath: string,
  content: string,
  check: boolean
): Promise<boolean> {
  const existing = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, 'utf8')
    : null;
  if (existing === content) {
    return false;
  }
  if (check) {
    console.error(`Stale: ${path.relative(REPO_ROOT, filePath)}`);
    process.exitCode = 1;
    return true;
  }
  fs.writeFileSync(filePath, content);
  return true;
}

async function main() {
  const check = process.argv.includes('--check');
  const config = readSourceConfig();
  const repo = resolveCheckout(config);

  const distTags = npmDistTags();
  const releases: Release[] = [];
  for (const version of config.versions) {
    const npmVersion = distTags.get(version);
    if (!npmVersion) {
      throw new Error(
        `npm has no '${version}-stable' dist-tag for ${NPM_PACKAGE}. ` +
          `Known: ${[...distTags.keys()].sort().join(', ')}`
      );
    }
    releases.push(readRelease(repo, version, npmVersion));
  }

  const prettierOptions = await prettier.resolveConfig(OUT_TABLE);
  const table = await prettier.format(renderTable(releases), {
    ...prettierOptions,
    parser: 'markdown',
  });

  await writeIfChanged(
    OUT_JSON,
    JSON.stringify(releases, null, 2) + '\n',
    check
  );
  await writeIfChanged(OUT_TABLE, table, check);

  warnAboutUnversionedReleases(distTags, config.versions);

  console.log(
    `${check ? 'Checked' : 'Wrote'} TV release metadata for ` +
      `${releases.map(r => r.version).join(', ')}`
  );
}

/**
 * Reports released versions that have no docs version.
 *
 * This never writes website/versions.json. That file is Docusaurus's own
 * manifest and must match the directories under website/versioned_docs, so
 * writing it from npm tags breaks the build with a missing-directory error.
 * Cutting a version is `yarn version:cut`.
 */
function warnAboutUnversionedReleases(
  distTags: Map<string, string>,
  configured: string[]
): void {
  const versionsPath = path.join(REPO_ROOT, 'website', 'versions.json');
  const docsVersions: string[] = JSON.parse(
    fs.readFileSync(versionsPath, 'utf8')
  );
  const missing = configured.filter(v => !docsVersions.includes(v));
  if (missing.length > 0) {
    console.warn(
      `Configured in tv-source.json but absent from website/versions.json: ` +
        `${missing.join(', ')}. Run \`yarn --cwd website version:cut <version>\`.`
    );
  }
}

await main();
