/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Generates TV prop-table partials from react-native-tvos' generated types.
 *
 * Prose and examples stay hand-written in docs/; only the prop lists are
 * generated, so they cannot drift from the shipped API. Output is committed,
 * which keeps `yarn start` working for contributors with no TV checkout and
 * makes an upstream prop rename visible in review.
 *
 * Usage: node scripts/src/generate-tv-api.ts [--repo=<path>] [--check]
 */

import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

import {
  API_SNAPSHOT_PATH,
  REPO_ROOT,
  readGeneratedType,
  readSourceConfig,
  resolveCheckout,
  resolveCommit,
  readAtRef,
  existsAtRef,
} from './lib/rntv-source.ts';
import {extractMembers, parse, type Member} from './lib/tv-api-extract.ts';

const OUT_DIR = path.join(REPO_ROOT, 'docs', '_tv-generated');

const TV = 'Libraries/Components/TV';
const SCROLL_VIEW = 'Libraries/Components/ScrollView/ScrollView.d.ts';

type Target = {
  /** Output basename under docs/_tv-generated/. */
  out: string;
  /** Source file, relative to types_generated/. */
  file: string;
  /** Declaration to read members from. */
  decl: string;
  /** When set, only these members are emitted, and all must exist. */
  only?: string[];
  /** Heading shown above the table. */
  title: string;
};

const TARGETS: Target[] = [
  {
    out: 'tv-view-props',
    file: `${TV}/TVViewPropTypes.d.ts`,
    decl: 'TVViewProps',
    title: 'TV props',
  },
  {
    out: 'tv-parallax-properties',
    file: `${TV}/TVViewPropTypes.d.ts`,
    decl: 'TVParallaxPropertiesType',
    title: 'TVParallaxProperties',
  },
  {
    out: 'tv-focus-guide-view-props',
    file: `${TV}/TVFocusGuideView.d.ts`,
    decl: 'TVFocusGuideViewProps',
    title: 'TVFocusGuideView props',
  },
  {
    out: 'tv-focus-guide-view-methods',
    file: `${TV}/TVFocusGuideView.d.ts`,
    decl: 'TVFocusGuideViewImperativeMethods',
    title: 'TVFocusGuideView methods',
  },
  {
    out: 'tv-event-control-methods',
    file: `${TV}/TVEventControl.d.ts`,
    decl: 'TVEventControl',
    title: 'TVEventControl methods',
  },
  {
    out: 'tv-event-handler-methods',
    file: `${TV}/TVEventHandler.d.ts`,
    decl: 'TVEventHandlerType',
    title: 'TVEventHandler methods',
  },
  {
    out: 'tv-remote-event',
    file: `${TV}/TVEventHandler.d.ts`,
    decl: 'TVRemoteEvent',
    title: 'TVRemoteEvent',
  },
  {
    out: 'tv-remote-event-body',
    file: `${TV}/TVEventHandler.d.ts`,
    decl: 'TVRemoteEventBody',
    title: 'TVRemoteEvent body',
  },
  {
    out: 'tv-scroll-view-props',
    file: SCROLL_VIEW,
    decl: 'ScrollViewBaseProps',
    only: [
      'scrollAnimationDuration',
      'scrollAnimationEasing',
      'scrollAnimationEnabled',
      'snapToItemPadding',
    ],
    title: 'TV scroll props',
  },
];

/** Escapes text for a Markdown table cell inside MDX. */
function cell(text: string): string {
  return text
    .replace(/\|/g, '\\|')
    .replace(/</g, '&lt;')
    .replace(/\{/g, '&#123;')
    .replace(/\n+/g, '<br />')
    .trim();
}

function platformBadges(platforms: string[]): string {
  return platforms.map(p => `<div className="label ${p}">${p}</div>`).join(' ');
}

function describe(member: Member): string {
  const parts: string[] = [];
  if (member.deprecated !== null) {
    parts.push(`**Deprecated.** ${member.deprecated}`.trim());
  }
  if (member.description) {
    parts.push(member.description);
  }
  return parts.join('\n') || '—';
}

function renderTable(target: Target, members: Member[]): string {
  const rows = members.map(m => {
    const name = platformBadges(m.platforms)
      ? `\`${m.name}\` ${platformBadges(m.platforms)}`
      : `\`${m.name}\``;
    return `| ${name} | \`${cell(m.type)}\` | ${m.required ? 'Yes' : 'No'} | ${cell(describe(m))} |`;
  });
  // These partials are imported into MDX pages, so they are compiled as MDX.
  // HTML comments are a syntax error there; MDX expression comments are not.
  return [
    `{/* @generated by scripts/src/generate-tv-api.ts from`,
    `    react-native-tvos ${target.file} (${target.decl}).`,
    `    Do not edit by hand; run \`yarn generate:tv-api\`. */}`,
    '',
    `| Name | Type | Required | Description |`,
    `| ---- | ---- | -------- | ----------- |`,
    ...rows,
    '',
  ].join('\n');
}

/** Member names already present in the committed partials. */
function documentedInCommittedPartials(): Set<string> {
  const names = new Set<string>();
  for (const target of TARGETS) {
    const file = path.join(OUT_DIR, `${target.out}.md`);
    if (!fs.existsSync(file)) {
      throw new Error(
        `Missing docs/_tv-generated/${target.out}.md. Run \`yarn generate:tv-api\`.`
      );
    }
    for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
      const name = /^\|\s*`([A-Za-z_$][\w$]*)`/.exec(line)?.[1];
      if (name) {
        names.add(name);
      }
    }
  }
  return names;
}

/**
 * Checks the shipped API against the committed partials, without regenerating.
 *
 * This is the CI gate. It needs only the committed ReactNativeApi.d.ts, read
 * from a git ref, so it runs without the `yarn build-types` output that full
 * generation requires and that is gitignored upstream.
 */
function surfaceOnly(): void {
  const config = readSourceConfig();
  const repo = resolveCheckout(config);
  crossCheck(repo, config.apiRef, documentedInCommittedPartials());
  if (!process.exitCode) {
    console.log(
      `Every TV member in the public API appears in docs/_tv-generated.`
    );
  }
}

async function main() {
  if (process.argv.includes('--surface')) {
    surfaceOnly();
    return;
  }
  const check = process.argv.includes('--check');
  const config = readSourceConfig();
  const repo = resolveCheckout(config);
  const commit = resolveCommit(repo, config.apiRef);

  const prettierOptions = await prettier.resolveConfig(
    path.join(OUT_DIR, 'x.md')
  );

  const sources = new Map<string, ReturnType<typeof readGeneratedType>>();
  const written: Record<string, string> = {};
  const documented = new Set<string>();

  fs.mkdirSync(OUT_DIR, {recursive: true});

  for (const target of TARGETS) {
    if (!sources.has(target.file)) {
      sources.set(target.file, readGeneratedType(repo, target.file));
    }
    const source = sources.get(target.file)!;
    const members = extractMembers(
      parse(target.file, source.text),
      target.decl,
      target.only
    );
    members.forEach(m => documented.add(m.name));

    const formatted = await prettier.format(renderTable(target, members), {
      ...prettierOptions,
      parser: 'markdown',
    });
    const outPath = path.join(OUT_DIR, `${target.out}.md`);
    const existing = fs.existsSync(outPath)
      ? fs.readFileSync(outPath, 'utf8')
      : null;
    if (existing !== formatted) {
      if (check) {
        console.error(`Stale: docs/_tv-generated/${target.out}.md`);
        process.exitCode = 1;
      } else {
        fs.writeFileSync(outPath, formatted);
      }
    }
    written[target.out] = `${target.file}#${target.decl}`;
  }

  const manifest =
    JSON.stringify(
      {
        source: config.repo,
        ref: config.apiRef,
        commit,
        inputs: Object.fromEntries(
          [...sources.values()].map(s => [s.relPath, s.signedSource])
        ),
        outputs: written,
      },
      null,
      2
    ) + '\n';
  const manifestPath = path.join(OUT_DIR, 'manifest.json');
  const existingManifest = fs.existsSync(manifestPath)
    ? fs.readFileSync(manifestPath, 'utf8')
    : null;
  if (existingManifest !== manifest && !check) {
    fs.writeFileSync(manifestPath, manifest);
  }

  crossCheck(repo, config.apiRef, documented);

  console.log(
    `${check ? 'Checked' : 'Wrote'} ${TARGETS.length} TV partials from ` +
      `${config.repo} @ ${commit.slice(0, 9)}`
  );
}

/**
 * Snapshot declarations whose members must all be documented.
 *
 * The snapshot contains BOTH the deprecated hand-maintained types and the
 * generated ones, and api-extractor disambiguates the collisions with `_N`
 * and `_default` suffixes. The generated side is authoritative, so these are
 * deliberately the suffixed names:
 *
 * - `TVViewProps` is generated; `TVProps` is the deprecated manual type, which
 *   still lists onFocus/onBlur and omits autoFocus/destinations/scrollSnap*.
 * - `TVRemoteEvent_2` is generated; `TVRemoteEvent` is the deprecated manual
 *   type, which still carries a `target` field the fork no longer emits.
 * - `TVEventControl_default` holds the members; `TVEventControl` is a
 *   `typeof` alias of it.
 *
 * Auditing the deprecated names instead reports props that no longer ship.
 */
const SNAPSHOT_AUDIT = [
  'TVViewProps',
  'TVFocusGuideViewProps',
  'TVParallaxPropertiesType',
  'TVRemoteEvent_2',
  'TVRemoteEventBody',
  'TVEventControl_default',
];

/**
 * Fails when the shipped API declares a TV member the docs never mention.
 *
 * ReactNativeApi.d.ts is committed, so this runs from a git ref with no
 * build-types run, which is what makes it usable as a cheap CI gate. It
 * compares member names rather than type names: the snapshot renames and
 * rolls up types (TVViewProps becomes TVProps, TVViewPropsIOS is a bare
 * alias), so type-name comparison is pure noise.
 *
 * The reverse direction is not checked. The snapshot omits `declare module`
 * augmentations and mangles identifiers, so a name absent from it proves
 * nothing.
 */
function crossCheck(repo: string, ref: string, documented: Set<string>): void {
  if (!existsAtRef(repo, ref, API_SNAPSHOT_PATH)) {
    console.warn(
      `No ${API_SNAPSHOT_PATH} at ${ref}; skipped the completeness check.`
    );
    return;
  }
  const allowPath = path.join(REPO_ROOT, 'scripts', 'tv-api-allowlist.json');
  const allowed: string[] = fs.existsSync(allowPath)
    ? JSON.parse(fs.readFileSync(allowPath, 'utf8')).undocumented
    : [];

  const snapshot = parse(
    API_SNAPSHOT_PATH,
    readAtRef(repo, ref, API_SNAPSHOT_PATH)
  );

  const missing: string[] = [];
  for (const decl of SNAPSHOT_AUDIT) {
    let members: Member[];
    try {
      members = extractMembers(snapshot, decl);
    } catch {
      console.warn(`Snapshot has no '${decl}'; it may have been renamed.`);
      continue;
    }
    for (const member of members) {
      if (!documented.has(member.name) && !allowed.includes(member.name)) {
        missing.push(`${decl}.${member.name}`);
      }
    }
  }

  if (missing.length > 0) {
    console.error(
      `These TV members ship in the public API but appear in no generated ` +
        `partial:\n` +
        missing.map(m => `  - ${m}`).join('\n') +
        `\n\nAdd them to a target in TARGETS, or record the omission in ` +
        `scripts/tv-api-allowlist.json.`
    );
    process.exitCode = 1;
  }
}

await main();
