/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Generates the react-native-tvos release metadata table.
 *
 * Released versions come from npm dist-tags, not git tags. The fork's
 * repository also carries inherited upstream core React Native tags (v0.87.1,
 * v0.86.3), which are not TV releases; and the fork's own `-N` suffix means
 * "newer", the opposite of semver's prerelease ordering, so sorting git tags
 * with a semver library picks the wrong release. The `<version>-stable`
 * dist-tags published to npm are authoritative.
 *
 * Per-version platform requirements are read through `git show` at each
 * `tvos-v<version>.0` ref.
 *
 * Usage: node scripts/src/generate-tv-releases.ts [--repo=<path>] [--check]
 */

import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

import {
  REPO_ROOT,
  fetchPackage,
  readPackageFile,
  readSourceConfig,
  type TvPackage,
} from './lib/rntv-source.ts';

const OUT_JSON = path.join(REPO_ROOT, 'website', 'tv-releases.json');
const OUT_TABLE = path.join(
  REPO_ROOT,
  'website',
  'releases',
  '_tv-branches-table.md'
);

type Release = {
  version: string;
  npmVersion: string;
  distTag: string;
  react: string;
  minTvos: string;
  minSdk: string;
  targetSdk: string;
  compileSdk: string;
  ndkVersion: string;
};

function matchOrThrow(text: string, re: RegExp, what: string): string {
  const captured = re.exec(text)?.[1];
  if (captured === undefined) {
    throw new Error(
      `Could not read ${what}. The source layout may have changed.`
    );
  }
  return captured;
}

function readRelease(pkg: TvPackage): Release {
  const manifest = JSON.parse(readPackageFile(pkg, 'package.json'));
  const react = manifest.peerDependencies?.react;
  if (!react) {
    throw new Error(`No react peer dependency in ${pkg.distTag}.`);
  }

  const gradle = readPackageFile(pkg, 'gradle/libs.versions.toml');
  const podHelpers = readPackageFile(pkg, 'scripts/cocoapods/helpers.rb');

  return {
    version: pkg.label,
    npmVersion: pkg.version,
    distTag: pkg.distTag,
    react,
    minTvos: matchOrThrow(
      podHelpers,
      /def self\.min_ios_version_supported\s*\n\s*return '([\d.]+)'/,
      `min tvOS version in ${pkg.distTag}`
    ),
    minSdk: matchOrThrow(
      gradle,
      /^minSdk = "(\d+)"/m,
      `minSdk in ${pkg.distTag}`
    ),
    targetSdk: matchOrThrow(
      gradle,
      /^targetSdk = "(\d+)"/m,
      `targetSdk in ${pkg.distTag}`
    ),
    compileSdk: matchOrThrow(
      gradle,
      /^compileSdk = "(\d+)"/m,
      `compileSdk in ${pkg.distTag}`
    ),
    ndkVersion: matchOrThrow(
      gradle,
      /^ndkVersion = "([\d.]+)"/m,
      `ndkVersion in ${pkg.distTag}`
    ),
  };
}

const NPM_URL = 'https://www.npmjs.com/package/react-native-tvos/v';

function renderTable(releases: Release[]): string {
  const rows = releases.map(r =>
    [
      `\`${r.distTag}\``,
      `[\`${r.npmVersion}\`](${NPM_URL}/${r.npmVersion})`,
      `[\`${r.version}\`](https://reactnative.dev/versions)`,
      `\`${r.react}\``,
      `\`${r.minTvos}\``,
      `\`${r.minSdk}\``,
      `\`${r.targetSdk}\` / \`${r.compileSdk}\``,
      `\`${r.ndkVersion}\``,
    ].join(' | ')
  );
  // Imported into an MDX page, so HTML comments are a syntax error here.
  return [
    '{/* @generated by scripts/src/generate-tv-releases.ts.',
    '    Do not edit by hand; run `yarn generate:tv-releases`. */}',
    '',
    '| Release | `react-native-tvos` | Core RN | React | Min tvOS | Android `minSdk` | `targetSdk` / `compileSdk` | NDK |',
    '| ------- | ------------------- | ------- | ----- | -------- | ---------------- | -------------------------- | --- |',
    ...rows.map(row => `| ${row} |`),
    '',
  ].join('\n');
}

async function writeIfChanged(
  filePath: string,
  content: string,
  check: boolean
): Promise<boolean> {
  const existing = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, 'utf8')
    : null;
  if (existing === content) {
    return false;
  }
  if (check) {
    console.error(`Stale: ${path.relative(REPO_ROOT, filePath)}`);
    process.exitCode = 1;
    return true;
  }
  fs.writeFileSync(filePath, content);
  return true;
}

async function main() {
  const check = process.argv.includes('--check');
  const config = readSourceConfig();

  const releases: Release[] = [];
  for (const [version, distTag] of Object.entries(config.versions)) {
    releases.push(readRelease(fetchPackage(config.package, distTag, version)));
  }

  const prettierOptions = await prettier.resolveConfig(OUT_TABLE);
  const table = await prettier.format(renderTable(releases), {
    ...prettierOptions,
    parser: 'markdown',
  });

  await writeIfChanged(
    OUT_JSON,
    JSON.stringify(releases, null, 2) + '\n',
    check
  );
  await writeIfChanged(OUT_TABLE, table, check);

  warnAboutUnversionedReleases(Object.keys(config.versions));

  console.log(
    `${check ? 'Checked' : 'Wrote'} TV release metadata for ` +
      `${releases.map(r => r.version).join(', ')}`
  );
}

/**
 * Reports released versions that have no docs version.
 *
 * This never writes website/versions.json. That file is Docusaurus's own
 * manifest and must match the directories under website/versioned_docs, so
 * writing it from npm tags breaks the build with a missing-directory error.
 * Cutting a version is `yarn version:cut`.
 */
function warnAboutUnversionedReleases(configured: string[]): void {
  const versionsPath = path.join(REPO_ROOT, 'website', 'versions.json');
  const docsVersions: string[] = JSON.parse(
    fs.readFileSync(versionsPath, 'utf8')
  );
  const missing = configured.filter(v => !docsVersions.includes(v));
  if (missing.length > 0) {
    console.warn(
      `Configured in tv-source.json but absent from website/versions.json: ` +
        `${missing.join(', ')}. Run \`yarn --cwd website version:cut <version>\`.`
    );
  }
}

await main();
